package com.devops.govtables.services;

import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;

@Service
public class CfopServices {

    public List<Cfop> getListCfops(){
        List<Cfop> cfops = new ArrayList<Cfop>();
        cfops.add(new Cfop(1000,"ENTRADAS OU AQUISIÇÕES DE SERVIÇOS DO ESTADO","Sintético"));
        cfops.add(new Cfop(1100,"COMPRAS PARA INDUTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS","Sintético"));
        cfops.add(new Cfop(1101,"Compra para industrialização","Analítico"));
        cfops.add(new Cfop(1102,"Compra para comercialização","Analítico"));
        cfops.add(new Cfop(1111,"Compra para industrialização de mercadoria recebida anteriormente em consignação industrial","Analítico"));
        cfops.add(new Cfop(1113,"Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil","Analítico"));
        cfops.add(new Cfop(1116,"Compra para industrialização originada de encomenda para recebimento futuro","Analítico"));
        cfops.add(new Cfop(1117,"Compra para comercialização originada de encomenda para recebimento futuro","Analítico"));
        cfops.add(new Cfop(1118,"Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem","Analítico"));
        cfops.add(new Cfop(1120,"Compra para industrialização, em venda à ordem, já recebida do vendedor remetente","Analítico"));
        cfops.add(new Cfop(1121,"Compra para comercialização, em venda à ordem, já recebida do vendedor remetente","Analítico"));
        cfops.add(new Cfop(1122,"Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente","Analítico"));
        cfops.add(new Cfop(1124,"Industrialização efetuada por outra empresa","Analítico"));
        cfops.add(new Cfop(1125,"Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria","Analítico"));
        cfops.add(new Cfop(1126,"Compra para utilização na prestação de serviço","Analítico"));
        cfops.add(new Cfop(1128,"Compra para utilização na prestação de serviço sujeita ao ISSQN","Analítico"));
        cfops.add(new Cfop(1131,"Entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, decorrente de operação de ato cooperativo.","Analítico"));
        cfops.add(new Cfop(1132,"Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização","Analítico"));
        cfops.add(new Cfop(1135,"Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização.","Analítico"));
        cfops.add(new Cfop(1150,"TRANSFERÊNCIAS PARA INDUSTRIAZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS","Sintético"));
        cfops.add(new Cfop(1151,"Transferência para industrialização","Analítico"));
        cfops.add(new Cfop(1152,"Transferência para comercialização","Analítico"));
        cfops.add(new Cfop(1153,"Transferência de energia elétrica para distribuição","Analítico"));
        cfops.add(new Cfop(1154,"Transferência para utilização na prestação de serviço","Analítico"));
        cfops.add(new Cfop(1159,"Entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo","Analítico"));
        cfops.add(new Cfop(1200,"DEVOLUÇÕES DE VENDAS DE PRODUÇÃO, DE TERCEIROS OU ANULAÇÕES DE VALORES","Sintético"));
        cfops.add(new Cfop(1201,"Devolução de venda de produção do estabelecimento","Analítico"));
        cfops.add(new Cfop(1202,"Devolução de venda de mercadoria adquirida ou recebida de terceiros","Analítico"));
        cfops.add(new Cfop(1203,"Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","Analítico"));
        cfops.add(new Cfop(1204,"Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","Analítico"));
        cfops.add(new Cfop(1205,"Anulação de valor relativo à prestação de serviço de comunicação","Analítico"));
        cfops.add(new Cfop(1206,"Anulação de valor relativo à prestação de serviço de transporte","Analítico"));
        cfops.add(new Cfop(1207,"Anulação de valor relativo à venda de energia elétrica","Analítico"));
        cfops.add(new Cfop(1208,"Devolução de produção do estabelecimento, remetida em transferência","Analítico"));
        cfops.add(new Cfop(1209,"Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência","Analítico"));
        cfops.add(new Cfop(1212,"Devolução de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)","Analítico"));
        cfops.add(new Cfop(1213,"Devolução de remessa de produção do estabelecimento com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.","Analítico"));
        cfops.add(new Cfop(1214,"Devolução de fixação de preço de produção do estabelecimento produtor, de ato cooperativo.","Analítico"));
        cfops.add(new Cfop(1215,"Devolução de fornecimento de produção do estabelecimento de ato cooperativo","Analítico"));
        cfops.add(new Cfop(1216,"Devolução de fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo","Analítico"));
        cfops.add(new Cfop(1250,"COMPRAS DE ENERGIA ELÉTRICA","Sintético"));
        cfops.add(new Cfop(1251,"Compra de energia elétrica para distribuição ou comercialização","Analítico"));
        cfops.add(new Cfop(1252,"Compra de energia elétrica por estabelecimento industrial","Analítico"));
        cfops.add(new Cfop(1253,"Compra de energia elétrica por estabelecimento comercial","Analítico"));
        cfops.add(new Cfop(1254,"Compra de energia elétrica por estabelecimento prestador de serviço de transporte","Analítico"));
        cfops.add(new Cfop(1255,"Compra de energia elétrica por estabelecimento prestador de serviço de comunicação","Analítico"));
        cfops.add(new Cfop(1256,"Compra de energia elétrica por estabelecimento de produtor rural","Analítico"));
        cfops.add(new Cfop(1257,"Compra de energia elétrica para consumo por demanda contratada","Analítico"));
        cfops.add(new Cfop(1300,"AQUISIÇÕES DE SERVIÇOS DE COMUNICAÇÃO","Sintético"));
        cfops.add(new Cfop(1301,"Aquisição de serviço de comunicação para execução de serviço da mesma natureza","Analítico"));
        cfops.add(new Cfop(1302,"Aquisição de serviço de comunicação por estabelecimento industrial","Analítico"));
        cfops.add(new Cfop(1303,"Aquisição de serviço de comunicação por estabelecimento comercial","Analítico"));
        cfops.add(new Cfop(1304,"Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte","Analítico"));
        cfops.add(new Cfop(1305,"Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica","Analítico"));
        cfops.add(new Cfop(1306,"Aquisição de serviço de comunicação por estabelecimento de produtor rural","Analítico"));
        cfops.add(new Cfop(1350,"AQUISIÇÕES DE SERVIÇOS DE TRANSPORTE","Sintético"));
        cfops.add(new Cfop(1351,"Aquisição de serviço de transporte para execução de serviço da mesma natureza","Analítico"));
        cfops.add(new Cfop(1352,"Aquisição de serviço de transporte por estabelecimento industrial","Analítico"));
        cfops.add(new Cfop(1353,"Aquisição de serviço de transporte por estabelecimento comercial","Analítico"));
        cfops.add(new Cfop(1354,"Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação","Analítico"));
        cfops.add(new Cfop(1355,"Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica","Analítico"));
        cfops.add(new Cfop(1356,"Aquisição de serviço de transporte por estabelecimento de produtor rural","Analítico"));
        cfops.add(new Cfop(1360,"Aquisição de serviço de transporte por contribuinte substituto em relação ao serviço de transporte.","Analítico"));
        cfops.add(new Cfop(1400,"ENTRADAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA","Sintético"));
        cfops.add(new Cfop(1401,"Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(1403,"Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(1406,"Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(1407,"Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(1408,"Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(1409,"Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(1410,"Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(1411,"Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(1414,"Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(1415,"Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(1450,"SISTEMAS DE INTEGRAÇÃO E PARCERIA RURAL","Sintético"));
        cfops.add(new Cfop(1451,"Entrada de animal - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(1452,"Entrada de insumo - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(1453,"Retorno do animal ou da produção - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(1454,"Retorno simbólico do animal ou da produção - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(1455,"Retorno de insumo não utilizado na produção - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(1456,"Entrada referente a remuneração do produtor no Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(1500,"ENTRADAS DE MERCADORIAS REMETIDAS PARA FORMAÇÃO DE LOTE OU COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES","Sintético"));
        cfops.add(new Cfop(1501,"Entrada de mercadoria recebida com fim específico de exportação","Analítico"));
        cfops.add(new Cfop(1503,"Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento","Analítico"));
        cfops.add(new Cfop(1504,"Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros","Analítico"));
        cfops.add(new Cfop(1505,"Entrada decorrente de devolução de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.","Analítico"));
        cfops.add(new Cfop(1506,"Entrada decorrente de devolução de mercadorias, adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação","Analítico"));
        cfops.add(new Cfop(1550,"OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO","Sintético"));
        cfops.add(new Cfop(1551,"Compra de bem para o ativo imobilizado","Analítico"));
        cfops.add(new Cfop(1552,"Transferência de bem do ativo imobilizado","Analítico"));
        cfops.add(new Cfop(1553,"Devolução de venda de bem do ativo imobilizado","Analítico"));
        cfops.add(new Cfop(1554,"Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(1555,"Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento","Analítico"));
        cfops.add(new Cfop(1556,"Compra de material para uso ou consumo","Analítico"));
        cfops.add(new Cfop(1557,"Transferência de material para uso ou consumo","Analítico"));
        cfops.add(new Cfop(1600,"CRÉDITOS E RESSARCIMENTOS DE ICMS","Sintético"));
        cfops.add(new Cfop(1601,"Recebimento, por transferência, de crédito de ICMS","Analítico"));
        cfops.add(new Cfop(1602,"Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento da mesma empresa, para compensação de saldo devedor de ICMS","Analítico"));
        cfops.add(new Cfop(1603,"Ressarcimento de ICMS retido por substituição tributária","Analítico"));
        cfops.add(new Cfop(1604,"Lançamento do crédito relativo à compra de bem para o ativo imobilizado","Analítico"));
        cfops.add(new Cfop(1605,"Recebimento, por transferência, de saldo devedor de ICMS de outro estabelecimento da mesma empresa.","Analítico"));
        cfops.add(new Cfop(1650,"ENTRADAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES","Sintético"));
        cfops.add(new Cfop(1651,"Compra de combustível ou lubrificante para industrialização subseqüente","Analítico"));
        cfops.add(new Cfop(1652,"Compra de combustível ou lubrificante para comercialização","Analítico"));
        cfops.add(new Cfop(1653,"Compra de combustível ou lubrificante por consumidor ou usuário final","Analítico"));
        cfops.add(new Cfop(1657,"Retorno de remessa de combustível ou lubrificante para venda fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(1658,"Transferência de combustível e lubrificante para industrialização","Analítico"));
        cfops.add(new Cfop(1659,"Transferência de combustível e lubrificante para comercialização","Analítico"));
        cfops.add(new Cfop(1660,"Devolução de venda de combustível ou lubrificante destinado à industrialização subseqüente","Analítico"));
        cfops.add(new Cfop(1661,"Devolução de venda de combustível ou lubrificante destinado à comercialização","Analítico"));
        cfops.add(new Cfop(1662,"Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final","Analítico"));
        cfops.add(new Cfop(1663,"Entrada de combustível ou lubrificante para armazenagem","Analítico"));
        cfops.add(new Cfop(1664,"Retorno de combustível ou lubrificante remetido para armazenagem","Analítico"));
        cfops.add(new Cfop(1900,"OUTRAS ENTRADAS DE MERCADORIAS OU AQUISIÇÕES E SERVIÇOS","Sintético"));
        cfops.add(new Cfop(1901,"Entrada para industrialização por encomenda","Analítico"));
        cfops.add(new Cfop(1902,"Retorno de mercadoria remetida para industrialização por encomenda","Analítico"));
        cfops.add(new Cfop(1903,"Entrada de mercadoria remetida para industrialização e não aplicada no referido processo","Analítico"));
        cfops.add(new Cfop(1904,"Retorno de remessa para venda fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(1905,"Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral","Analítico"));
        cfops.add(new Cfop(1906,"Retorno de mercadoria remetida para depósito fechado ou armazém geral","Analítico"));
        cfops.add(new Cfop(1907,"Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral","Analítico"));
        cfops.add(new Cfop(1908,"Entrada de bem por conta de contrato de comodato ou locação","Analítico"));
        cfops.add(new Cfop(1909,"Retorno de bem remetido por conta de contrato de comodato ou locação","Analítico"));
        cfops.add(new Cfop(1910,"Entrada de bonificação, doação ou brinde","Analítico"));
        cfops.add(new Cfop(1911,"Entrada de amostra grátis","Analítico"));
        cfops.add(new Cfop(1912,"Entrada de mercadoria ou bem recebido para demonstração","Analítico"));
        cfops.add(new Cfop(1913,"Retorno de mercadoria ou bem remetido para demonstração","Analítico"));
        cfops.add(new Cfop(1914,"Retorno de mercadoria ou bem remetido para exposição ou feira","Analítico"));
        cfops.add(new Cfop(1915,"Entrada de mercadoria ou bem recebido para conserto ou reparo","Analítico"));
        cfops.add(new Cfop(1916,"Retorno de mercadoria ou bem remetido para conserto ou reparo","Analítico"));
        cfops.add(new Cfop(1917,"Entrada de mercadoria recebida em consignação mercantil ou industrial","Analítico"));
        cfops.add(new Cfop(1918,"Devolução de mercadoria remetida em consignação mercantil ou industrial","Analítico"));
        cfops.add(new Cfop(1919,"Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial","Analítico"));
        cfops.add(new Cfop(1920,"Entrada de vasilhame ou sacaria","Analítico"));
        cfops.add(new Cfop(1921,"Retorno de vasilhame ou sacaria","Analítico"));
        cfops.add(new Cfop(1922,"Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro","Analítico"));
        cfops.add(new Cfop(1923,"Entrada de mercadoria recebida do vendedor remetente, em venda à ordem","Analítico"));
        cfops.add(new Cfop(1924,"Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente","Analítico"));
        cfops.add(new Cfop(1925,"Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente","Analítico"));
        cfops.add(new Cfop(1926,"Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação","Analítico"));
        cfops.add(new Cfop(1931,"Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço. (Ajuste SINIEF 03/04)","Analítico"));
        cfops.add(new Cfop(1932,"Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador. (ajuste sinief 03/04)","Analítico"));
        cfops.add(new Cfop(1933,"Aquisição de serviço tributado pelo ISSQN.(ajuste sinief 03/04)","Analítico"));
        cfops.add(new Cfop(1934,"Entrada simbólica de mercadoria recebida para depósito fechado ou armazém geral","Analítico"));
        cfops.add(new Cfop(1949,"Outra entrada de mercadoria ou prestação de serviço não especificada","Analítico"));
        cfops.add(new Cfop(2000,"ENTRADAS OU AQUISIÇÕES DE SERVIÇOS DE OUTROS ESTADOS","Sintético"));
        cfops.add(new Cfop(2100,"COMPRAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS","Sintético"));
        cfops.add(new Cfop(2101,"Compra para industrialização","Analítico"));
        cfops.add(new Cfop(2102,"Compra para comercialização","Analítico"));
        cfops.add(new Cfop(2111,"Compra para industrialização de mercadoria recebida anteriormente em consignação industrial","Analítico"));
        cfops.add(new Cfop(2113,"Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil","Analítico"));
        cfops.add(new Cfop(2116,"Compra para industrialização originada de encomenda para recebimento futuro","Analítico"));
        cfops.add(new Cfop(2117,"Compra para comercialização originada de encomenda para recebimento futuro","Analítico"));
        cfops.add(new Cfop(2118,"Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem","Analítico"));
        cfops.add(new Cfop(2120,"Compra para industrialização, em venda à ordem, já recebida do vendedor remetente","Analítico"));
        cfops.add(new Cfop(2121,"Compra para comercialização, em venda à ordem, já recebida do vendedor remetente","Analítico"));
        cfops.add(new Cfop(2122,"Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente","Analítico"));
        cfops.add(new Cfop(2124,"Industrialização efetuada por outra empresa","Analítico"));
        cfops.add(new Cfop(2125,"Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria","Analítico"));
        cfops.add(new Cfop(2126,"Compra para utilização na prestação de serviço","Analítico"));
        cfops.add(new Cfop(2128,"Compra para utilização na prestação de serviço sujeita ao ISSQN","Analítico"));
        cfops.add(new Cfop(2131,"Entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, decorrente de operação de ato cooperativo.","Analítico"));
        cfops.add(new Cfop(2132,"Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização.","Analítico"));
        cfops.add(new Cfop(2135,"Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização.","Analítico"));
        cfops.add(new Cfop(2150,"TRANSFERÊNCIAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS","Sintético"));
        cfops.add(new Cfop(2151,"Transferência para industrialização","Analítico"));
        cfops.add(new Cfop(2152,"Transferência para comercialização","Analítico"));
        cfops.add(new Cfop(2153,"Transferência de energia elétrica para distribuição","Analítico"));
        cfops.add(new Cfop(2154,"Transferência para utilização na prestação de serviço","Analítico"));
        cfops.add(new Cfop(2159,"Entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo","Analítico"));
        cfops.add(new Cfop(2200,"DEVOLUÇÕES DE VENDAS DE PRODUÇÃO PRÓPRIA, DE TERCEIROS OU ANULAÇÕES DE VALORES","Sintético"));
        cfops.add(new Cfop(2201,"Devolução de venda de produção do estabelecimento","Analítico"));
        cfops.add(new Cfop(2202,"Devolução de venda de mercadoria adquirida ou recebida de terceiros","Analítico"));
        cfops.add(new Cfop(2203,"Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","Analítico"));
        cfops.add(new Cfop(2204,"Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","Analítico"));
        cfops.add(new Cfop(2205,"Anulação de valor relativo à prestação de serviço de comunicação","Analítico"));
        cfops.add(new Cfop(2206,"Anulação de valor relativo à prestação de serviço de transporte","Analítico"));
        cfops.add(new Cfop(2207,"Anulação de valor relativo à venda de energia elétrica","Analítico"));
        cfops.add(new Cfop(2208,"Devolução de produção do estabelecimento, remetida em transferência","Analítico"));
        cfops.add(new Cfop(2209,"Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência","Analítico"));
        cfops.add(new Cfop(2212,"Devolução de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)","Analítico"));
        cfops.add(new Cfop(2213,"Devolução de remessa de produção do estabelecimento com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.","Analítico"));
        cfops.add(new Cfop(2214,"Devolução de fixação de preço de produção do estabelecimento produtor, de ato cooperativo.","Analítico"));
        cfops.add(new Cfop(2215,"Devolução de fornecimento de produção do estabelecimento de ato cooperativo","Analítico"));
        cfops.add(new Cfop(2216,"Devolução de fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo","Analítico"));
        cfops.add(new Cfop(2250,"COMPRAS DE ENERGIA ELÉTRICA","Sintético"));
        cfops.add(new Cfop(2251,"Compra de energia elétrica para distribuição ou comercialização","Analítico"));
        cfops.add(new Cfop(2252,"Compra de energia elétrica por estabelecimento industrial","Analítico"));
        cfops.add(new Cfop(2253,"Compra de energia elétrica por estabelecimento comercial","Analítico"));
        cfops.add(new Cfop(2254,"Compra de energia elétrica por estabelecimento prestador de serviço de transporte","Analítico"));
        cfops.add(new Cfop(2255,"Compra de energia elétrica por estabelecimento prestador de serviço de comunicação","Analítico"));
        cfops.add(new Cfop(2256,"Compra de energia elétrica por estabelecimento de produtor rural","Analítico"));
        cfops.add(new Cfop(2257,"Compra de energia elétrica para consumo por demanda contratada","Analítico"));
        cfops.add(new Cfop(2300,"AQUISIÇÕES DE SERVIÇOS DE COMUNICAÇÃO","Sintético"));
        cfops.add(new Cfop(2301,"Aquisição de serviço de comunicação para execução de serviço da mesma natureza","Analítico"));
        cfops.add(new Cfop(2302,"Aquisição de serviço de comunicação por estabelecimento industrial","Analítico"));
        cfops.add(new Cfop(2303,"Aquisição de serviço de comunicação por estabelecimento comercial","Analítico"));
        cfops.add(new Cfop(2304,"Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte","Analítico"));
        cfops.add(new Cfop(2305,"Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica","Analítico"));
        cfops.add(new Cfop(2306,"Aquisição de serviço de comunicação por estabelecimento de produtor rural","Analítico"));
        cfops.add(new Cfop(2350,"AQUISIÇÕES DE SERVIÇOS DE TRANSPORTE","Sintético"));
        cfops.add(new Cfop(2351,"Aquisição de serviço de transporte para execução de serviço da mesma natureza","Analítico"));
        cfops.add(new Cfop(2352,"Aquisição de serviço de transporte por estabelecimento industrial","Analítico"));
        cfops.add(new Cfop(2353,"Aquisição de serviço de transporte por estabelecimento comercial","Analítico"));
        cfops.add(new Cfop(2354,"Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação","Analítico"));
        cfops.add(new Cfop(2355,"Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica","Analítico"));
        cfops.add(new Cfop(2356,"Aquisição de serviço de transporte por estabelecimento de produtor rural","Analítico"));
        cfops.add(new Cfop(2400,"ENTRADAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUÇÃO TRIBUTÁRIA","Sintético"));
        cfops.add(new Cfop(2401,"Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(2403,"Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(2406,"Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(2407,"Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(2408,"Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(2409,"Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(2410,"Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(2411,"Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(2414,"Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(2415,"Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(2450,"SISTEMAS DE INTEGRAÇÃO E PARCERIA RURAL","Sintético"));
        cfops.add(new Cfop(2451,"Entrada de animal - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(2452,"Entrada de insumo - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(2453,"Retorno do animal ou da produção - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(2454,"Retorno simbólico do animal ou da produção - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(2455,"Retorno de insumo não utilizado na produção - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(2456,"Entrada referente a remuneração do produtor no Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(2500,"ENTRADAS DE MERCADORIAS REMETIDAS PARA FORMAÇÃO DE LOTE OU COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES","Sintético"));
        cfops.add(new Cfop(2501,"Entrada de mercadoria recebida com fim específico de exportação","Analítico"));
        cfops.add(new Cfop(2503,"Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento","Analítico"));
        cfops.add(new Cfop(2504,"Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros","Analítico"));
        cfops.add(new Cfop(2505,"Entrada decorrente de devolução de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento","Analítico"));
        cfops.add(new Cfop(2506,"Entrada decorrente de devolução de mercadorias, adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação","Analítico"));
        cfops.add(new Cfop(2550,"OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO","Sintético"));
        cfops.add(new Cfop(2551,"Compra de bem para o ativo imobilizado","Analítico"));
        cfops.add(new Cfop(2552,"Transferência de bem do ativo imobilizado","Analítico"));
        cfops.add(new Cfop(2553,"Devolução de venda de bem do ativo imobilizado","Analítico"));
        cfops.add(new Cfop(2554,"Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(2555,"Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento","Analítico"));
        cfops.add(new Cfop(2556,"Compra de material para uso ou consumo","Analítico"));
        cfops.add(new Cfop(2557,"Transferência de material para uso ou consumo","Analítico"));
        cfops.add(new Cfop(2600,"CRÉDITOS E RESSARCIMENTO DE ICMS","Sintético"));
        cfops.add(new Cfop(2603,"Ressarcimento de ICMS retido por substituição tributária","Analítico"));
        cfops.add(new Cfop(2650,"ENTRADAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETROLÉO E LUBRIFICANTES","Sintético"));
        cfops.add(new Cfop(2651,"Compra de combustível ou lubrificante para industrialização subseqüente","Analítico"));
        cfops.add(new Cfop(2652,"Compra de combustível ou lubrificante para comercialização","Analítico"));
        cfops.add(new Cfop(2653,"Compra de combustível ou lubrificante por consumidor ou usuário final","Analítico"));
        cfops.add(new Cfop(2657,"Retorno de remessa de combustível ou lubrificante para venda fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(2658,"Transferência de combustível e lubrificante para industrialização","Analítico"));
        cfops.add(new Cfop(2659,"Transferência de combustível e lubrificante para comercialização","Analítico"));
        cfops.add(new Cfop(2660,"Devolução de venda de combustível ou lubrificante destinado à industrialização subseqüente","Analítico"));
        cfops.add(new Cfop(2661,"Devolução de venda de combustível ou lubrificante destinado à comercialização","Analítico"));
        cfops.add(new Cfop(2662,"Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final","Analítico"));
        cfops.add(new Cfop(2663,"Entrada de combustível ou lubrificante para armazenagem","Analítico"));
        cfops.add(new Cfop(2664,"Retorno de combustível ou lubrificante remetido para armazenagem","Analítico"));
        cfops.add(new Cfop(2900,"OUTRAS ENTRADAS DE MERCADORIA OU AQUISIÇÕES DE SERVIÇOS","Sintético"));
        cfops.add(new Cfop(2901,"Entrada para industrialização por encomenda","Analítico"));
        cfops.add(new Cfop(2902,"Retorno de mercadoria remetida para industrialização por encomenda","Analítico"));
        cfops.add(new Cfop(2903,"Entrada de mercadoria remetida para industrialização e não aplicada no referido processo","Analítico"));
        cfops.add(new Cfop(2904,"Retorno de remessa para venda fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(2905,"Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral","Analítico"));
        cfops.add(new Cfop(2906,"Retorno de mercadoria remetida para depósito fechado ou armazém geral","Analítico"));
        cfops.add(new Cfop(2907,"Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral","Analítico"));
        cfops.add(new Cfop(2908,"Entrada de bem por conta de contrato de comodato ou locação","Analítico"));
        cfops.add(new Cfop(2909,"Retorno de bem remetido por conta de contrato de comodato ou locação","Analítico"));
        cfops.add(new Cfop(2910,"Entrada de bonificação, doação ou brinde","Analítico"));
        cfops.add(new Cfop(2911,"Entrada de amostra grátis","Analítico"));
        cfops.add(new Cfop(2912,"Entrada de mercadoria ou bem recebido para demonstração","Analítico"));
        cfops.add(new Cfop(2913,"Retorno de mercadoria ou bem remetido para demonstração","Analítico"));
        cfops.add(new Cfop(2914,"Retorno de mercadoria ou bem remetido para exposição ou feira","Analítico"));
        cfops.add(new Cfop(2915,"Entrada de mercadoria ou bem recebido para conserto ou reparo","Analítico"));
        cfops.add(new Cfop(2916,"Retorno de mercadoria ou bem remetido para conserto ou reparo","Analítico"));
        cfops.add(new Cfop(2917,"Entrada de mercadoria recebida em consignação mercantil ou industrial","Analítico"));
        cfops.add(new Cfop(2918,"Devolução de mercadoria remetida em consignação mercantil ou industrial","Analítico"));
        cfops.add(new Cfop(2919,"Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial","Analítico"));
        cfops.add(new Cfop(2920,"Entrada de vasilhame ou sacaria","Analítico"));
        cfops.add(new Cfop(2921,"Retorno de vasilhame ou sacaria","Analítico"));
        cfops.add(new Cfop(2922,"Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro","Analítico"));
        cfops.add(new Cfop(2923,"Entrada de mercadoria recebida do vendedor remetente, em venda à ordem","Analítico"));
        cfops.add(new Cfop(2924,"Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente","Analítico"));
        cfops.add(new Cfop(2925,"Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente","Analítico"));
        cfops.add(new Cfop(2931,"Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço. (ajuste sinief 03/04)","Analítico"));
        cfops.add(new Cfop(2932,"Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador. (ajuste sinief 03/04)","Analítico"));
        cfops.add(new Cfop(2933,"Aquisição de serviço tributado pelo ISSQN. (ajuste sinief 03/04)","Analítico"));
        cfops.add(new Cfop(2934,"Entrada simbólica de mercadoria recebida para depósito fechado ou armazém geral","Analítico"));
        cfops.add(new Cfop(2949,"Outra entrada de mercadoria ou prestação de serviço não especificado","Analítico"));
        cfops.add(new Cfop(3000,"ENTRADAS OU AQUISIÇÕES DE SERVIÇOS DO EXTERIOR","Sintético"));
        cfops.add(new Cfop(3100,"COMPRAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS","Sintético"));
        cfops.add(new Cfop(3101,"Compra para industrialização","Analítico"));
        cfops.add(new Cfop(3102,"Compra para comercialização","Analítico"));
        cfops.add(new Cfop(3126,"Compra para utilização na prestação de serviço","Analítico"));
        cfops.add(new Cfop(3127,"Compra para industrialização sob o regime de drawback","Analítico"));
        cfops.add(new Cfop(3128,"Compra para utilização na prestação de serviço sujeita ao ISSQN","Analítico"));
        cfops.add(new Cfop(3129,"Compra para industrialização sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)","Analítico"));
        cfops.add(new Cfop(3200,"DEVOLUÇÕES DE VENDAS DE PRODUÇÃO PRÓPRIA, DE TERCEIROS OU ANULAÇÕES DE VALORES","Sintético"));
        cfops.add(new Cfop(3201,"Devolução de venda de produção do estabelecimento","Analítico"));
        cfops.add(new Cfop(3202,"Devolução de venda de mercadoria adquirida ou recebida de terceiros","Analítico"));
        cfops.add(new Cfop(3205,"Anulação de valor relativo à prestação de serviço de comunicação","Analítico"));
        cfops.add(new Cfop(3206,"Anulação de valor relativo à prestação de serviço de transporte","Analítico"));
        cfops.add(new Cfop(3207,"Anulação de valor relativo à venda de energia elétrica","Analítico"));
        cfops.add(new Cfop(3211,"Devolução de venda de produção do estabelecimento sob o regime de drawback","Analítico"));
        cfops.add(new Cfop(3212,"Devolução de venda no mercado externo de mercadoria industrializada sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)","Analítico"));
        cfops.add(new Cfop(3250,"COMPRAS DE ENERGIA ELÉTRICA","Sintético"));
        cfops.add(new Cfop(3251,"Compra de energia elétrica para distribuição ou comercialização","Analítico"));
        cfops.add(new Cfop(3300,"AQUISIÇÕES DE SERVIÇOS DE COMUNICAÇÃO","Sintético"));
        cfops.add(new Cfop(3301,"Aquisição de serviço de comunicação para execução de serviço da mesma natureza","Analítico"));
        cfops.add(new Cfop(3350,"AQUISIÇÕES DE SERVIÇOS DE TRANSPORTE","Sintético"));
        cfops.add(new Cfop(3351,"Aquisição de serviço de transporte para execução de serviço da mesma natureza","Analítico"));
        cfops.add(new Cfop(3352,"Aquisição de serviço de transporte por estabelecimento industrial","Analítico"));
        cfops.add(new Cfop(3353,"Aquisição de serviço de transporte por estabelecimento comercial","Analítico"));
        cfops.add(new Cfop(3354,"Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação","Analítico"));
        cfops.add(new Cfop(3355,"Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica","Analítico"));
        cfops.add(new Cfop(3356,"Aquisição de serviço de transporte por estabelecimento de produtor rural","Analítico"));
        cfops.add(new Cfop(3500,"ENTRADAS DE MERCADORIAS REMETIDAS COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES","Sintético"));
        cfops.add(new Cfop(3503,"Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação","Analítico"));
        cfops.add(new Cfop(3550,"OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO E CONSUMO","Sintético"));
        cfops.add(new Cfop(3551,"Compra de bem para o ativo imobilizado","Analítico"));
        cfops.add(new Cfop(3553,"Devolução de venda de bem do ativo imobilizado","Analítico"));
        cfops.add(new Cfop(3556,"Compra de material para uso ou consumo","Analítico"));
        cfops.add(new Cfop(3650,"ENTRADAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES","Sintético"));
        cfops.add(new Cfop(3651,"Compra de combustível ou lubrificante para industrialização subseqüente","Analítico"));
        cfops.add(new Cfop(3652,"Compra de combustível ou lubrificante para comercialização","Analítico"));
        cfops.add(new Cfop(3653,"Compra de combustível ou lubrificante por consumidor ou usuário final","Analítico"));
        cfops.add(new Cfop(3900,"OUTRAS ENTRADAS DE MERCADORIAS OU AQUISIÇÕES DE SERVIÇOS","Sintético"));
        cfops.add(new Cfop(3930,"Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária","Analítico"));
        cfops.add(new Cfop(3949,"Outra entrada de mercadoria ou prestação de serviço não especificado","Analítico"));
        cfops.add(new Cfop(5000,"SAÍDAS OU PRESTAÇÕES DE SERVIÇOS PARA O ESTADO","Sintético"));
        cfops.add(new Cfop(5100,"VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS","Sintético"));
        cfops.add(new Cfop(5101,"Venda de produçãoo do estabelecimento","Analítico"));
        cfops.add(new Cfop(5102,"Venda de mercadoria adquirida ou recebida de terceiros","Analítico"));
        cfops.add(new Cfop(5103,"Venda de produção do estabelecimento, efetuada fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(5104,"Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(5105,"Venda de produção do estabelecimento que não deva por ele transitar","Analítico"));
        cfops.add(new Cfop(5106,"Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar","Analítico"));
        cfops.add(new Cfop(5109,"Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","Analítico"));
        cfops.add(new Cfop(5110,"Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","Analítico"));
        cfops.add(new Cfop(5111,"Venda de produção do estabelecimento remetida anteriormente em consignação industrial","Analítico"));
        cfops.add(new Cfop(5112,"Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial","Analítico"));
        cfops.add(new Cfop(5113,"Venda de produção do estabelecimento remetida anteriormente em consignação mercantil","Analítico"));
        cfops.add(new Cfop(5114,"Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil","Analítico"));
        cfops.add(new Cfop(5115,"Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil","Analítico"));
        cfops.add(new Cfop(5116,"Venda de produção do estabelecimento originada de encomenda para entrega futura","Analítico"));
        cfops.add(new Cfop(5117,"Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura","Analítico"));
        cfops.add(new Cfop(5118,"Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem","Analítico"));
        cfops.add(new Cfop(5119,"Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem","Analítico"));
        cfops.add(new Cfop(5120,"Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem","Analítico"));
        cfops.add(new Cfop(5122,"Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente","Analítico"));
        cfops.add(new Cfop(5123,"Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente","Analítico"));
        cfops.add(new Cfop(5124,"Industrialização efetuada para outra empresa","Analítico"));
        cfops.add(new Cfop(5125,"Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria","Analítico"));
        cfops.add(new Cfop(5129,"Venda de insumo importado e de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped","Analítico"));
        cfops.add(new Cfop(5131,"Remessa de produção do estabelecimento, com previsão de posterior ajuste ou fixação de preço, de ato cooperativo.","Analítico"));
        cfops.add(new Cfop(5132,"Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço de ato cooperativo.","Analítico"));
        cfops.add(new Cfop(5150,"TRANSFERÊNCIAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS","Sintético"));
        cfops.add(new Cfop(5151,"Transferência de produção do estabelecimento","Analítico"));
        cfops.add(new Cfop(5152,"Transferência de mercadoria adquirida ou recebida de terceiros","Analítico"));
        cfops.add(new Cfop(5153,"Transferência de energia elétrica","Analítico"));
        cfops.add(new Cfop(5155,"Transferência de produção do estabelecimento, que não deva por ele transitar","Analítico"));
        cfops.add(new Cfop(5156,"Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar","Analítico"));
        cfops.add(new Cfop(5159,"Fornecimento de produção do estabelecimento de ato cooperativo","Analítico"));
        cfops.add(new Cfop(5160,"Fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo","Analítico"));
        cfops.add(new Cfop(5200,"DEVOLUÇÕES DE COMPRAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU ANULAÇÕES DE VALORES","Sintético"));
        cfops.add(new Cfop(5201,"Devolução de compra para industrialização","Analítico"));
        cfops.add(new Cfop(5202,"Devolução de compra para comercialização","Analítico"));
        cfops.add(new Cfop(5205,"Anulação de valor relativo a aquisição de serviço de comunicação","Analítico"));
        cfops.add(new Cfop(5206,"Anulação de valor relativo a aquisição de serviço de transporte","Analítico"));
        cfops.add(new Cfop(5207,"Anulação de valor relativo à compra de energia elétrica","Analítico"));
        cfops.add(new Cfop(5208,"Devolução de mercadoria recebida em transferência para industrialização","Analítico"));
        cfops.add(new Cfop(5209,"Devolução de mercadoria recebida em transferência para comercialização","Analítico"));
        cfops.add(new Cfop(5210,"Devolução de compra para utilização na prestação de serviço","Analítico"));
        cfops.add(new Cfop(5213,"Devolução de entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.","Analítico"));
        cfops.add(new Cfop(5214,"Devolução de fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo, para comercialização.","Analítico"));
        cfops.add(new Cfop(5215,"Devolução de fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo, para industrialização.","Analítico"));
        cfops.add(new Cfop(5216,"Devolução de entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo","Analítico"));
        cfops.add(new Cfop(5250,"VENDAS DE ENERGIA ELÉTRICA","Sintético"));
        cfops.add(new Cfop(5251,"Venda de energia elétrica para distribuição ou comercialização","Analítico"));
        cfops.add(new Cfop(5252,"Venda de energia elétrica para estabelecimento industrial","Analítico"));
        cfops.add(new Cfop(5253,"Venda de energia elétrica para estabelecimento comercial","Analítico"));
        cfops.add(new Cfop(5254,"Venda de energia elétrica para estabelecimento prestador de serviço de transporte","Analítico"));
        cfops.add(new Cfop(5255,"Venda de energia elétrica para estabelecimento prestador de serviço de comunicação","Analítico"));
        cfops.add(new Cfop(5256,"Venda de energia elétrica para estabelecimento de produtor rural","Analítico"));
        cfops.add(new Cfop(5257,"Venda de energia elétrica para consumo por demanda contratada","Analítico"));
        cfops.add(new Cfop(5258,"Venda de energia elétrica a não contribuinte","Analítico"));
        cfops.add(new Cfop(5300,"PRESTAÇÕES DE SERVIÇOS DE COMUNICAÇÃO","Sintético"));
        cfops.add(new Cfop(5301,"Prestação de serviço de comunicação para execução de serviço da mesma natureza","Analítico"));
        cfops.add(new Cfop(5302,"Prestação de serviço de comunicação a estabelecimento industrial","Analítico"));
        cfops.add(new Cfop(5303,"Prestação de serviço de comunicação a estabelecimento comercial","Analítico"));
        cfops.add(new Cfop(5304,"Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte","Analítico"));
        cfops.add(new Cfop(5305,"Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica","Analítico"));
        cfops.add(new Cfop(5306,"Prestação de serviço de comunicação a estabelecimento de produtor rural","Analítico"));
        cfops.add(new Cfop(5307,"Prestação de serviço de comunicação a não contribuinte","Analítico"));
        cfops.add(new Cfop(5350,"PRESTAÇÕES DE SERVIÇOS DE TRANSPORTE","Sintético"));
        cfops.add(new Cfop(5351,"Prestação de serviço de transporte para execução de serviço da mesma natureza","Analítico"));
        cfops.add(new Cfop(5352,"Prestação de serviço de transporte a estabelecimento industrial","Analítico"));
        cfops.add(new Cfop(5353,"Prestação de serviço de transporte a estabelecimento comercial","Analítico"));
        cfops.add(new Cfop(5354,"Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação","Analítico"));
        cfops.add(new Cfop(5355,"Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica","Analítico"));
        cfops.add(new Cfop(5356,"Prestação de serviço de transporte a estabelecimento de produtor rural","Analítico"));
        cfops.add(new Cfop(5357,"Prestação de serviço de transporte a não contribuinte","Analítico"));
        cfops.add(new Cfop(5359,"Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal. (ajuste sinief 03/04)","Analítico"));
        cfops.add(new Cfop(5360,"Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte.","Analítico"));
        cfops.add(new Cfop(5400,"SAÍDAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA","Sintético"));
        cfops.add(new Cfop(5401,"Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto","Analítico"));
        cfops.add(new Cfop(5402,"Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto","Analítico"));
        cfops.add(new Cfop(5403,"Venda de mercadoria, adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte-substituto","Analítico"));
        cfops.add(new Cfop(5405,"Venda de mercadoria, adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte-substituído","Analítico"));
        cfops.add(new Cfop(5408,"Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(5409,"Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(5410,"Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(5411,"Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(5412,"Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(5413,"Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária.","Analítico"));
        cfops.add(new Cfop(5414,"Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(5415,"Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(5450,"SISTEMAS DE INTEGRAÇÃO E PARCERIA RURAL","Sintético"));
        cfops.add(new Cfop(5451,"Remessa de animal - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(5452,"Remessa de insumo - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(5453,"Retorno de animal ou da produção - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(5454,"Retorno simbólico de animal ou da produção - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(5455,"Retorno de insumos não utilizados na produção - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(5456,"Saída referente a remuneração do produtor - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(5500,"REMESSAS PARA FORMAÇÃO DE LOTE E COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVETUAIS DEVOLUÇÕES","Sintético"));
        cfops.add(new Cfop(5501,"Remessa de produção do estabelecimento, com fim específico de exportação","Analítico"));
        cfops.add(new Cfop(5502,"Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação","Analítico"));
        cfops.add(new Cfop(5503,"Devolução de mercadoria recebida com fim específico de exportação","Analítico"));
        cfops.add(new Cfop(5504,"Remessa de mercadorias para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.","Analítico"));
        cfops.add(new Cfop(5505,"Remessa de mercadorias, adquiridas ou recebidas de terceiros, para formação de lote de exportação","Analítico"));
        cfops.add(new Cfop(5550,"OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO","Sintético"));
        cfops.add(new Cfop(5551,"Venda de bem do ativo imobilizado","Analítico"));
        cfops.add(new Cfop(5552,"Transferência de bem do ativo imobilizado","Analítico"));
        cfops.add(new Cfop(5553,"Devolução de compra de bem para o ativo imobilizado","Analítico"));
        cfops.add(new Cfop(5554,"Remessa de bem do ativo imobilizado para uso fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(5555,"Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento","Analítico"));
        cfops.add(new Cfop(5556,"Devolução de compra de material de uso ou consumo","Analítico"));
        cfops.add(new Cfop(5557,"Transferência de material de uso ou consumo","Analítico"));
        cfops.add(new Cfop(5600,"CRÉDITOS E RESSARCIMENTOS DE ICMS","Sintético"));
        cfops.add(new Cfop(5601,"Transferência de crédito de ICMS acumulado","Analítico"));
        cfops.add(new Cfop(5602,"Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS","Analítico"));
        cfops.add(new Cfop(5603,"Ressarcimento de ICMS retido por substituição tributária","Analítico"));
        cfops.add(new Cfop(5605,"Transferência de saldo devedor de ICMS de outro estabelecimento da mesma empresa. (ajuste sinief 03/04)","Analítico"));
        cfops.add(new Cfop(5606,"Utilização de saldo credor de ICMS para extinção por compensação de débitos fiscais.","Analítico"));
        cfops.add(new Cfop(5650,"SAÍDAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES","Sintético"));
        cfops.add(new Cfop(5651,"Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente","Analítico"));
        cfops.add(new Cfop(5652,"Venda de combustível ou lubrificante de produção do estabelecimento destinado à comercialização","Analítico"));
        cfops.add(new Cfop(5653,"Venda de combustível ou lubrificante de produção do estabelecimento destinado a consumidor ou usuário final","Analítico"));
        cfops.add(new Cfop(5654,"Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente","Analítico"));
        cfops.add(new Cfop(5655,"Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização","Analítico"));
        cfops.add(new Cfop(5656,"Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado a consumidor ou usuário final","Analítico"));
        cfops.add(new Cfop(5657,"Remessa de combustível ou lubrificante adquirido ou recebido de terceiros para venda fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(5658,"Transferência de combustível ou lubrificante de produção do estabelecimento","Analítico"));
        cfops.add(new Cfop(5659,"Transferência de combustível ou lubrificante adquirido ou recebido de terceiro","Analítico"));
        cfops.add(new Cfop(5660,"Devolução de compra de combustível ou lubrificante adquirido para industrialização subseqüente","Analítico"));
        cfops.add(new Cfop(5661,"Devolução de compra de combustível ou lubrificante adquirido para comercialização","Analítico"));
        cfops.add(new Cfop(5662,"Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final","Analítico"));
        cfops.add(new Cfop(5663,"Remessa para armazenagem de combustível ou lubrificante","Analítico"));
        cfops.add(new Cfop(5664,"Retorno de combustível ou lubrificante recebido para armazenagem","Analítico"));
        cfops.add(new Cfop(5665,"Retorno simbólico de combustível ou lubrificante recebido para armazenagem","Analítico"));
        cfops.add(new Cfop(5666,"Remessa por conta e ordem de terceiros de combustível ou lubrificante recebido para armazenagem","Analítico"));
        cfops.add(new Cfop(5667,"Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra unidade da Federação","Analítico"));
        cfops.add(new Cfop(5900,"OUTRAS SAÍDAS DE MERCADORIAS OU PRESTAÇÕES DE SERVIÇOS","Sintético"));
        cfops.add(new Cfop(5901,"Remessa para industrialização por encomenda","Analítico"));
        cfops.add(new Cfop(5902,"Retorno de mercadoria utilizada na industrialização por encomenda","Analítico"));
        cfops.add(new Cfop(5903,"Retorno de mercadoria recebida para industrialização e não aplicada no referido processo","Analítico"));
        cfops.add(new Cfop(5904,"Remessa para venda fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(5905,"Remessa para depósito fechado ou armazém geral","Analítico"));
        cfops.add(new Cfop(5906,"Retorno de mercadoria depositada em depósito fechado ou armazém geral","Analítico"));
        cfops.add(new Cfop(5907,"Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral","Analítico"));
        cfops.add(new Cfop(5908,"Remessa de bem por conta de contrato de comodato ou locação","Analítico"));
        cfops.add(new Cfop(5909,"Retorno de bem recebido por conta de contrato de comodato ou locação","Analítico"));
        cfops.add(new Cfop(5910,"Remessa em bonificação, doação ou brinde","Analítico"));
        cfops.add(new Cfop(5911,"Remessa de amostra grátis","Analítico"));
        cfops.add(new Cfop(5912,"Remessa de mercadoria ou bem para demonstração","Analítico"));
        cfops.add(new Cfop(5913,"Retorno de mercadoria ou bem recebido para demonstração","Analítico"));
        cfops.add(new Cfop(5914,"Remessa de mercadoria ou bem para exposição ou feira","Analítico"));
        cfops.add(new Cfop(5915,"Remessa de mercadoria ou bem para conserto ou reparo","Analítico"));
        cfops.add(new Cfop(5916,"Retorno de mercadoria ou bem recebido para conserto ou reparo","Analítico"));
        cfops.add(new Cfop(5917,"Remessa de mercadoria em consignação mercantil ou industrial","Analítico"));
        cfops.add(new Cfop(5918,"Devolução de mercadoria recebida em consignação mercantil ou industrial","Analítico"));
        cfops.add(new Cfop(5919,"Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial","Analítico"));
        cfops.add(new Cfop(5920,"Remessa de vasilhame ou sacaria","Analítico"));
        cfops.add(new Cfop(5921,"Devolução de vasilhame ou sacaria","Analítico"));
        cfops.add(new Cfop(5922,"Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura","Analítico"));
        cfops.add(new Cfop(5923,"Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado","Analítico"));
        cfops.add(new Cfop(5924,"Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente","Analítico"));
        cfops.add(new Cfop(5925,"Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente","Analítico"));
        cfops.add(new Cfop(5926,"Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação","Analítico"));
        cfops.add(new Cfop(5927,"Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração","Analítico"));
        cfops.add(new Cfop(5928,"Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa","Analítico"));
        cfops.add(new Cfop(5929,"Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também acobertada por documento fiscal do varejo","Analítico"));
        cfops.add(new Cfop(5931,"Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço","Analítico"));
        cfops.add(new Cfop(5932,"Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador","Analítico"));
        cfops.add(new Cfop(5933,"Prestação de serviço tributado pelo ISSQN. (ajuste sinief 03/04)","Analítico"));
        cfops.add(new Cfop(5934,"Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado","Analítico"));
        cfops.add(new Cfop(5949,"Outra saída de mercadoria ou prestação de serviço não especificado","Analítico"));
        cfops.add(new Cfop(6000,"SAÍDAS OU PRESTAÇÕES DE SERVIÇOS PARA OUTROS ESTADOS","Sintético"));
        cfops.add(new Cfop(6100,"VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS","Sintético"));
        cfops.add(new Cfop(6101,"Venda de produção do estabelecimento","Analítico"));
        cfops.add(new Cfop(6102,"Venda de mercadoria adquirida ou recebida de terceiros","Analítico"));
        cfops.add(new Cfop(6103,"Venda de produção do estabelecimento, efetuada fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(6104,"Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(6105,"Venda de produção do estabelecimento que não deva por ele transitar","Analítico"));
        cfops.add(new Cfop(6106,"Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar","Analítico"));
        cfops.add(new Cfop(6107,"Venda de produção do estabelecimento, destinada a não contribuinte","Analítico"));
        cfops.add(new Cfop(6108,"Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte","Analítico"));
        cfops.add(new Cfop(6109,"Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","Analítico"));
        cfops.add(new Cfop(6110,"Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","Analítico"));
        cfops.add(new Cfop(6111,"Venda de produção do estabelecimento remetida anteriormente em consignação industrial","Analítico"));
        cfops.add(new Cfop(6112,"Venda de mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignação industrial","Analítico"));
        cfops.add(new Cfop(6113,"Venda de produção do estabelecimento remetida anteriormente em consignação mercantil","Analítico"));
        cfops.add(new Cfop(6114,"Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil","Analítico"));
        cfops.add(new Cfop(6115,"Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil","Analítico"));
        cfops.add(new Cfop(6116,"Venda de produção do estabelecimento originada de encomenda para entrega futura","Analítico"));
        cfops.add(new Cfop(6117,"Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura","Analítico"));
        cfops.add(new Cfop(6118,"Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem","Analítico"));
        cfops.add(new Cfop(6119,"Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem","Analítico"));
        cfops.add(new Cfop(6120,"Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem","Analítico"));
        cfops.add(new Cfop(6122,"Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente","Analítico"));
        cfops.add(new Cfop(6123,"Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente","Analítico"));
        cfops.add(new Cfop(6124,"Industrialização efetuada para outra empresa","Analítico"));
        cfops.add(new Cfop(6125,"Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria","Analítico"));
        cfops.add(new Cfop(6129,"Venda de insumo importado e de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)","Analítico"));
        cfops.add(new Cfop(6131,"Remessa de produção de estabelecimento, com previsão de posterior ajuste ou fixação de preço de ato cooperativo.","Analítico"));
        cfops.add(new Cfop(6132,"Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço ou fixação de preço de ato cooperativo.","Analítico"));
        cfops.add(new Cfop(6150,"TRANSFERÊNCIAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS","Sintético"));
        cfops.add(new Cfop(6151,"Transferência de produção do estabelecimento","Analítico"));
        cfops.add(new Cfop(6152,"Transferência de mercadoria adquirida ou recebida de terceiros","Analítico"));
        cfops.add(new Cfop(6153,"Transferência de energia elétrica","Analítico"));
        cfops.add(new Cfop(6155,"Transferência de produção do estabelecimento, que não deva por ele transitar","Analítico"));
        cfops.add(new Cfop(6156,"Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar","Analítico"));
        cfops.add(new Cfop(6159,"Fornecimento de produção do estabelecimento de ato cooperativo","Analítico"));
        cfops.add(new Cfop(6160,"Fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo","Analítico"));
        cfops.add(new Cfop(6200,"DEVOLUÇÕES DE COMPRAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU ANULAÇÕES DE VALORES","Sintético"));
        cfops.add(new Cfop(6201,"Devolução de compra para industrialização","Analítico"));
        cfops.add(new Cfop(6202,"Devolução de compra para comercialização","Analítico"));
        cfops.add(new Cfop(6205,"Anulação de valor relativo a aquisição de serviço de comunicação","Analítico"));
        cfops.add(new Cfop(6206,"Anulação de valor relativo a aquisição de serviço de transporte","Analítico"));
        cfops.add(new Cfop(6207,"Anulação de valor relativo à compra de energia elétrica","Analítico"));
        cfops.add(new Cfop(6208,"Devolução de mercadoria recebida em transferência para industrialização","Analítico"));
        cfops.add(new Cfop(6209,"Devolução de mercadoria recebida em transferência para comercialização","Analítico"));
        cfops.add(new Cfop(6210,"Devolução de compra para utilização na prestação de serviço","Analítico"));
        cfops.add(new Cfop(6213,"Devolução de entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, em ato cooperativo.","Analítico"));
        cfops.add(new Cfop(6214,"Devolução de fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo, para comercialização.","Analítico"));
        cfops.add(new Cfop(6215,"Devolução de fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, de ato cooperativo para industrialização.","Analítico"));
        cfops.add(new Cfop(6216,"Devolução de entrada decorrente do fornecimento de produto ou mercadoria de ato cooperativo","Analítico"));
        cfops.add(new Cfop(6250,"VENDAS DE ENERGIA ELÉTRICA","Sintético"));
        cfops.add(new Cfop(6251,"Venda de energia elétrica para distribuição ou comercialização","Analítico"));
        cfops.add(new Cfop(6252,"Venda de energia elétrica para estabelecimento industrial","Analítico"));
        cfops.add(new Cfop(6253,"Venda de energia elétrica para estabelecimento comercial","Analítico"));
        cfops.add(new Cfop(6254,"Venda de energia elétrica para estabelecimento prestador de serviço de transporte","Analítico"));
        cfops.add(new Cfop(6255,"Venda de energia elétrica para estabelecimento prestador de serviço de comunicação","Analítico"));
        cfops.add(new Cfop(6256,"Venda de energia elétrica para estabelecimento de produtor rural","Analítico"));
        cfops.add(new Cfop(6257,"Venda de energia elétrica para consumo por demanda contratada","Analítico"));
        cfops.add(new Cfop(6258,"Venda de energia elétrica a não contribuinte","Analítico"));
        cfops.add(new Cfop(6300,"PRESTAÇÕES DE SERVIÇOS DE COMUNICAÇÃO","Sintético"));
        cfops.add(new Cfop(6301,"Prestação de serviço de comunicação para execução de serviço da mesma natureza","Analítico"));
        cfops.add(new Cfop(6302,"Prestação de serviço de comunicação a estabelecimento industrial","Analítico"));
        cfops.add(new Cfop(6303,"Prestação de serviço de comunicação a estabelecimento comercial","Analítico"));
        cfops.add(new Cfop(6304,"Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte","Analítico"));
        cfops.add(new Cfop(6305,"Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica","Analítico"));
        cfops.add(new Cfop(6306,"Prestação de serviço de comunicação a estabelecimento de produtor rural","Analítico"));
        cfops.add(new Cfop(6307,"Prestação de serviço de comunicação a não contribuinte","Analítico"));
        cfops.add(new Cfop(6350,"PRESTAÇÕES DE SERVIÇOS DE TRANSPORTE","Sintético"));
        cfops.add(new Cfop(6351,"Prestação de serviço de transporte para execução de serviço da mesma natureza","Analítico"));
        cfops.add(new Cfop(6352,"Prestação de serviço de transporte a estabelecimento industrial","Analítico"));
        cfops.add(new Cfop(6353,"Prestação de serviço de transporte a estabelecimento comercial","Analítico"));
        cfops.add(new Cfop(6354,"Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação","Analítico"));
        cfops.add(new Cfop(6355,"Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica","Analítico"));
        cfops.add(new Cfop(6356,"Prestação de serviço de transporte a estabelecimento de produtor rural","Analítico"));
        cfops.add(new Cfop(6357,"Prestação de serviço de transporte a não contribuinte","Analítico"));
        cfops.add(new Cfop(6359,"Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal. (ajuste sinief 03/04)","Analítico"));
        cfops.add(new Cfop(6360,"Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte","Analítico"));
        cfops.add(new Cfop(6400,"SAÍDAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA","Sintético"));
        cfops.add(new Cfop(6401,"Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto","Analítico"));
        cfops.add(new Cfop(6402,"Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto","Analítico"));
        cfops.add(new Cfop(6403,"Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto","Analítico"));
        cfops.add(new Cfop(6404,"Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente","Analítico"));
        cfops.add(new Cfop(6408,"Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(6409,"Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(6410,"Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(6411,"Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(6412,"Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(6413,"Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(6414,"Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(6415,"Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária","Analítico"));
        cfops.add(new Cfop(6450,"SISTEMAS DE INTEGRAÇÃO E PARCERIA RURAL","Sintético"));
        cfops.add(new Cfop(6451,"Remessa de animal - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(6452,"Remessa de insumo - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(6453,"Retorno de animal ou da produção - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(6454,"Retorno simbólico de animal ou da produção - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(6455,"Retorno de insumos não utilizados na produção - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(6456,"Saída referente a remuneração do produtor - Sistema de Integração e Parceria Rural","Analítico"));
        cfops.add(new Cfop(6500,"REMESSAS PARA FORMAÇÃO DE LOTE E COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES","Sintético"));
        cfops.add(new Cfop(6501,"Remessa de produção do estabelecimento, com fim específico de exportação","Analítico"));
        cfops.add(new Cfop(6502,"Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação","Analítico"));
        cfops.add(new Cfop(6503,"Devolução de mercadoria recebida com fim específico de exportação","Analítico"));
        cfops.add(new Cfop(6504,"Remessa de mercadorias para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento.","Analítico"));
        cfops.add(new Cfop(6505,"Remessa de mercadorias, adquiridas ou recebidas de terceiros, para formação de lote de exportação","Analítico"));
        cfops.add(new Cfop(6550,"OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO","Sintético"));
        cfops.add(new Cfop(6551,"Venda de bem do ativo imobilizado","Analítico"));
        cfops.add(new Cfop(6552,"Transferência de bem do ativo imobilizado","Analítico"));
        cfops.add(new Cfop(6553,"Devolução de compra de bem para o ativo imobilizado","Analítico"));
        cfops.add(new Cfop(6554,"Remessa de bem do ativo imobilizado para uso fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(6555,"Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento","Analítico"));
        cfops.add(new Cfop(6556,"Devolução de compra de material de uso ou consumo","Analítico"));
        cfops.add(new Cfop(6557,"Transferência de material de uso ou consumo","Analítico"));
        cfops.add(new Cfop(6600,"CRÉDITOS E RESSARCIMENTOS DE ICMS","Sintético"));
        cfops.add(new Cfop(6603,"Ressarcimento de ICMS retido por substituição tributária","Analítico"));
        cfops.add(new Cfop(6650,"SAÍDAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES","Sintético"));
        cfops.add(new Cfop(6651,"Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente","Analítico"));
        cfops.add(new Cfop(6652,"Venda de combustível ou lubrificante de produção do estabelecimento destinado à comercialização","Analítico"));
        cfops.add(new Cfop(6653,"Venda de combustível ou lubrificante de produção do estabelecimento destinado a consumidor ou usuário final","Analítico"));
        cfops.add(new Cfop(6654,"Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente","Analítico"));
        cfops.add(new Cfop(6655,"Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à comercialização","Analítico"));
        cfops.add(new Cfop(6656,"Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado a consumidor ou usuário final","Analítico"));
        cfops.add(new Cfop(6657,"Remessa de combustível ou lubrificante adquirido ou recebido de terceiros para venda fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(6658,"Transferência de combustível ou lubrificante de produção do estabelecimento","Analítico"));
        cfops.add(new Cfop(6659,"Transferência de combustível ou lubrificante adquirido ou recebido de terceiro","Analítico"));
        cfops.add(new Cfop(6660,"Devolução de compra de combustível ou lubrificante adquirido para industrialização subseqüente","Analítico"));
        cfops.add(new Cfop(6661,"Devolução de compra de combustível ou lubrificante adquirido para comercialização","Analítico"));
        cfops.add(new Cfop(6662,"Devolução de compra de combustível ou lubrificante adquirido por consumidor ou usuário final","Analítico"));
        cfops.add(new Cfop(6663,"Remessa para armazenagem de combustível ou lubrificante","Analítico"));
        cfops.add(new Cfop(6664,"Retorno de combustível ou lubrificante recebido para armazenagem","Analítico"));
        cfops.add(new Cfop(6665,"Retorno simbólico de combustível ou lubrificante recebido para armazenagem","Analítico"));
        cfops.add(new Cfop(6666,"Remessa por conta e ordem de terceiros de combustível ou lubrificante recebido para armazenagem","Analítico"));
        cfops.add(new Cfop(6667,"Venda de combustível ou lubrificante a consumidor ou usuário final estabelecido em outra unidade da Federação diferente a da que ocorrer o consumo","Analítico"));
        cfops.add(new Cfop(6900,"OUTRAS SAÍDAS DE MERCADORIAS OU PRESTAÇÕES DE SERVIÇOS","Sintético"));
        cfops.add(new Cfop(6901,"Remessa para industrialização por encomenda","Analítico"));
        cfops.add(new Cfop(6902,"Retorno de mercadoria utilizada na industrialização por encomenda","Analítico"));
        cfops.add(new Cfop(6903,"Retorno de mercadoria recebida para industrialização e não aplicada no referido processo","Analítico"));
        cfops.add(new Cfop(6904,"Remessa para venda fora do estabelecimento","Analítico"));
        cfops.add(new Cfop(6905,"Remessa para depósito fechado ou armazém geral","Analítico"));
        cfops.add(new Cfop(6906,"Retorno de mercadoria depositada em depósito fechado ou armazém geral","Analítico"));
        cfops.add(new Cfop(6907,"Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral","Analítico"));
        cfops.add(new Cfop(6908,"Remessa de bem por conta de contrato de comodato ou locação","Analítico"));
        cfops.add(new Cfop(6909,"Retorno de bem recebido por conta de contrato de comodato ou locação","Analítico"));
        cfops.add(new Cfop(6910,"Remessa em bonificação, doação ou brinde","Analítico"));
        cfops.add(new Cfop(6911,"Remessa de amostra grátis","Analítico"));
        cfops.add(new Cfop(6912,"Remessa de mercadoria ou bem para demonstração","Analítico"));
        cfops.add(new Cfop(6913,"Retorno de mercadoria ou bem recebido para demonstração","Analítico"));
        cfops.add(new Cfop(6914,"Remessa de mercadoria ou bem para exposição ou feira","Analítico"));
        cfops.add(new Cfop(6915,"Remessa de mercadoria ou bem para conserto ou reparo","Analítico"));
        cfops.add(new Cfop(6916,"Retorno de mercadoria ou bem recebido para conserto ou reparo","Analítico"));
        cfops.add(new Cfop(6917,"Remessa de mercadoria em consignação mercantil ou industrial","Analítico"));
        cfops.add(new Cfop(6918,"Devolução de mercadoria recebida em consignação mercantil ou industrial","Analítico"));
        cfops.add(new Cfop(6919,"Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial","Analítico"));
        cfops.add(new Cfop(6920,"Remessa de vasilhame ou sacaria","Analítico"));
        cfops.add(new Cfop(6921,"Devolução de vasilhame ou sacaria","Analítico"));
        cfops.add(new Cfop(6922,"Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura","Analítico"));
        cfops.add(new Cfop(6923,"Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado","Analítico"));
        cfops.add(new Cfop(6924,"Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente","Analítico"));
        cfops.add(new Cfop(6925,"Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente","Analítico"));
        cfops.add(new Cfop(6929,"Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF","Analítico"));
        cfops.add(new Cfop(6931,"Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço","Analítico"));
        cfops.add(new Cfop(6932,"Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador","Analítico"));
        cfops.add(new Cfop(6933,"Prestação de serviço tributado pelo ISSQN (ajuste sinief 03/04)","Analítico"));
        cfops.add(new Cfop(6934,"Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado","Analítico"));
        cfops.add(new Cfop(6949,"Outra saída de mercadoria ou prestação de serviço não especificado","Analítico"));
        cfops.add(new Cfop(7000,"SAÍDAS OU PRESTAÇÕES DE SERVIÇOS PARA O EXTERIOR","Sintético"));
        cfops.add(new Cfop(7100,"VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS","Sintético"));
        cfops.add(new Cfop(7101,"Venda de produção do estabelecimento","Analítico"));
        cfops.add(new Cfop(7102,"Venda de mercadoria adquirida ou recebida de terceiros","Analítico"));
        cfops.add(new Cfop(7105,"Venda de produção do estabelecimento, que não deva por ele transitar","Analítico"));
        cfops.add(new Cfop(7106,"Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar","Analítico"));
        cfops.add(new Cfop(7127,"Venda de produção do estabelecimento sob o regime de drawback","Analítico"));
        cfops.add(new Cfop(7129,"Venda de produção do estabelecimento ao mercado externo de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)","Analítico"));
        cfops.add(new Cfop(7200,"DEVOLUÇÕES DE COMPRAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU ANULAÇÕES DE VALORES","Sintético"));
        cfops.add(new Cfop(7201,"Devolução de compra para industrialização","Analítico"));
        cfops.add(new Cfop(7202,"Devolução de compra para comercialização","Analítico"));
        cfops.add(new Cfop(7205,"Anulação de valor relativo à aquisição de serviço de comunicação","Analítico"));
        cfops.add(new Cfop(7206,"Anulação de valor relativo a aquisição de serviço de transporte","Analítico"));
        cfops.add(new Cfop(7207,"Anulação de valor relativo à compra de energia elétrica","Analítico"));
        cfops.add(new Cfop(7210,"Devolução de compra para utilização na prestação de serviço","Analítico"));
        cfops.add(new Cfop(7211,"Devolução de compras para industrialização sob o regime de drawback","Analítico"));
        cfops.add(new Cfop(7212,"Devolução de compras para industrialização sob o regime de Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)","Analítico"));
        cfops.add(new Cfop(7250,"VENDAS DE ENERGIA ELÉTRICA","Sintético"));
        cfops.add(new Cfop(7251,"Venda de energia elétrica para o exterior","Analítico"));
        cfops.add(new Cfop(7300,"PRESTAÇÕES DE SERVIÇOS DE COMUNICAÇÃO","Sintético"));
        cfops.add(new Cfop(7301,"Prestação de serviço de comunicação para execução de serviço da mesma natureza","Analítico"));
        cfops.add(new Cfop(7350,"PRESTAÇÕES DE SERVIÇOS DE TRANSPORTE","Sintético"));
        cfops.add(new Cfop(7358,"Prestação de serviço de transporte","Analítico"));
        cfops.add(new Cfop(7500,"EXPORTAÇÃO DE MERCADORIAS RECEBIDAS COM FIM ESPECÍFICO DE EXPORTAÇÃO","Sintético"));
        cfops.add(new Cfop(7501,"Exportação de mercadorias recebidas com fim específico de exportação","Analítico"));
        cfops.add(new Cfop(7504,"Exportação de mercadoria que foi objeto de formação de lote de exportação","Analítico"));
        cfops.add(new Cfop(7550,"OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO","Sintético"));
        cfops.add(new Cfop(7551,"Venda de bem do ativo imobilizado","Analítico"));
        cfops.add(new Cfop(7553,"Devolução de compra de bem para o ativo imobilizado","Analítico"));
        cfops.add(new Cfop(7556,"Devolução de compra de material de uso ou consumo","Analítico"));
        cfops.add(new Cfop(7650,"SAÍDAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO E LUBRIFICANTES","Sintético"));
        cfops.add(new Cfop(7651,"Venda de combustível ou lubrificante de produção do estabelecimento destinado à industrialização subseqüente","Analítico"));
        cfops.add(new Cfop(7654,"Venda de combustível ou lubrificante adquirido ou recebido de terceiros destinado à industrialização subseqüente","Analítico"));
        cfops.add(new Cfop(7667,"Venda de combustível ou lubrificante a consumidor ou usuário final","Analítico"));
        cfops.add(new Cfop(7900,"OUTRAS SAÍDAS DE MERCADORIAS OU PRESTAÇÕES DE SERVIÇOS","Sintético"));
        cfops.add(new Cfop(7930,"Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária","Analítico"));
        cfops.add(new Cfop(7949,"Outra saída de mercadoria ou prestação de serviço não especificado","Analítico"));
        return cfops;
    }

    public Cfop getCfop(Integer code) {
        Optional<Cfop> any = getListCfops()
                .stream()
                .filter(c -> c.getCode().equals(code))
                .findAny();

        if (any.isPresent()) {
            return any.get();
        }else {
            return new Cfop(0, "", "");
        }
    }
}
